const trackercontainer = require('../controllers/trackercontainer.controller');
const  express = require('express');
const trackercontainerroute = express.Router();
trackercontainerroute.post('/',trackercontainer.createTrackerContainer);
trackercontainerroute.get('/',trackercontainer.findAllContainersRelatedToUser);
trackercontainerroute.get('/',trackercontainer.findOneTrackerContainer);
trackercontainerroute.post('/',trackercontainer.joinTrackerContainer);
trackercontainerroute.post('/:trackercontainerid/trackercontainerinfo',trackercontainer.updateTrackerContainer);
trackercontainerroute.delete('/trackercontainerinfo',trackercontainer.deleteTCWithCCandTRandTCR);
module.exports =  trackercontainerroute;